# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: trusty

r: bioc-devel

r_github_packages:
 - hadley/devtools#1263
#before - Bioconductor-mirror/zlibbioc
# - Bioconductor-mirror/rhdf5
#after 
bioc_packages:
  - rhdf5
  - zlibbioc 

r_packages:
  - covr

include:
  - r: release
  - r: oldrel
  - r: devel

after_success:
  - Rscript -e 'library(covr); codecov()'
